### ISSUE TITLE
Plans for releasing R 3.6 package?

### ISSUE THREAD

**Issue by guptarajat** [conda-forge/r-feedstock#9]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by dpryan79** [comment]
Yes, R 3.6.1 is due out in one month and conda-forge will start building it then.

**Comment by guptarajat** [comment]
Thanks for the quick update.

**Comment by jdblischak** [comment]
@guptarajat FYI the repository to watch is [r-base-feedstock](https://github.com/conda-forge/r-base-feedstock). The recipe in this feedstock is a wrapper for conveniently installing r-base and r-recommended, so it won't be updated until after both of those feedstocks are updated.

https://anaconda.org/conda-forge/r-base
